### PR TITLE
fix(localized-rich-text-input): dropdown fix

### LINKED ISSUE #1195: LocalizedRichTextInput: Dropdown z-index problem
Screenshot 2019-11-25 at 09 46 48

### PR DESCRIPTION
**Pull request by montezume**
#### Summary

Fixes #1195

### CODE REVIEW

File: src/components/inputs/localized-rich-text-input/localized-rich-text-input.visualspec.js [hunk 1]
```diff
@@ -76,5 +83,31 @@ describe('LocalizedRichTextInput', () => {
 
     // check that there is now a strong tag in the document.
     numOfTags = await getNumberOfTags('strong');
+
```
Comment (montezume) [inline src/components/inputs/localized-rich-text-input/localized-rich-text-input.visualspec.js]: added Percy test so we can stop this regression in future

**Comment by montezume** [comment]
I trust in your trust of that test
