### PR TITLE
fix: LinkButton to use inline TextBody

### LINKED ISSUE #588: LinkButton should render the label in a <span> element
**Describe the bug**
The `<LinkButton>` renders the label in a `<Text.Body>` element, which defaults to `<p>`.
This becomes problematic when the `<LinkButton>` is rendered within a paragraph text, as nested `<p>` are not valid.

**To Reproduce**
image

https://codesandbox.io/s/k06ln8z2xr

**Expected behavior**
The `<LinkButton>` should render the label within a `<span>` element

### PR DESCRIPTION
**Pull request by jonnybel**
#### Summary

This PR:
- Updates documentation of `Text.Body` and `Text.Detail` to include the `isInline` prop.
- Fixes #588 by using the aforementioned prop.

#### Description

There is still a problem with the `LinkButton` rendering a `div` (from the `Spacings.Inline` wrapper), which inside a `p` is also an invalid DOM nesting. I shall address this in a follow-up PR.

### CODE REVIEW

File: src/components/buttons/link-button/link-button.js [hunk 1]
```diff
@@ -50,7 +50,7 @@ const LinkButton = props => (
           size: 'medium',
           theme: props.isDisabled ? 'grey' : 'green',
         })}
-      <Text.Body>{props.label}</Text.Body>
+      <Text.Body isInline>{props.label}</Text.Body>
```
Comment (tdeekens) [inline src/components/buttons/link-button/link-button.js]: Nit: `isInline={true}`. I didn't see us abbreviating that here. If we would maybe renaming to `inline` would be apt but I don't see that breaking change happening.

File: src/components/typography/text/README.md [hunk 2]
```diff
@@ -94,6 +94,7 @@ Wraps the given text in a `<p>` element, for normal content.
 | `children` | `PropTypes.node` |    ✅    | -                                                                             | -       |
 | `title`    | `String`         |    -     | -                                                                             | -       |
 | `truncate` | `Bool`           |    -     | -                                                                             | `false` |
+| `inline`   | `Bool`           |    -     | -                                                                             | `false` |
```
Comment (tdeekens) [inline src/components/typography/text/README.md]: `inline` or `isInline`? I am confused by the prop naming inconsistencies. When did it change and way if so from one convention to the other?

Comment (jonnybel) [reply src/components/typography/text/README.md]: Sorry, I copied the wrong thing and didn't even notice 🤦‍♂️

File: src/components/typography/text/README.md [hunk 3]
```diff
@@ -94,6 +94,7 @@ Wraps the given text in a `<p>` element, for normal content.
 | `children` | `PropTypes.node` |    ✅    | -                                                                             | -       |
 | `title`    | `String`         |    -     | -                                                                             | -       |
 | `truncate` | `Bool`           |    -     | -                                                                             | `false` |
+| `isInline` | `Bool`           |    -     | -                                                                             | `false` |
```
Comment (montezume) [inline src/components/typography/text/README.md]: is this used anywhere?

File: src/components/typography/text/README.md (hunk 2 above)
Comment (montezume) [reply src/components/typography/text/README.md]: I don't see this prop actually being used though? Shouldn't the default be "true" then?

File: src/components/typography/text/README.md (hunk 3 above)
Comment (emmenko) [reply src/components/typography/text/README.md]: This is the README of the Text component, I think the props was missing from the documentation...right?

Comment (jonnybel) [reply src/components/typography/text/README.md]: Yes, it was already being used, just not documented.

Comment (montezume) [reply src/components/typography/text/README.md]: oooh 🤦‍♂️
