### PR TITLE
fix: Right border of removable tag

### LINKED ISSUE #638: Tag component hover fix
It's been requested from design that when you hover on a tag link component that is removeable, the entire border of the rectangle highlights. Now it only highlights the left, bottom and right.

### PR DESCRIPTION
**Pull request by jonnybel**
#### Summary

Fixes #638 

Kapture 2019-04-05 at 14 23 46
(GIF compression messing those colours 🧐)

#### Description

Using a regular `border` doesn't fit the design because the border takes space and would add a little edge or a flicker between the tag and the removal button.

The easiest alternative would be using `box-shadow` to emulate the border, just on the right side, but when the tag has an onClick prop, it has a box-shadow of its own when hovered, so this new box-shadow border would have to be merged with the current box-shadow and added to the design tokens.
I didn't like where this was going so I tried another approach:

So I used an absolutely positioned `:after` pseudo-element, and it does the job.

### CODE REVIEW

**Comment by jonnybel** [comment]
I've added a fix to the focus styles for the [x] button to improve its a11y.

File: src/components/tag/tag.js [hunk 1]
```diff
@@ -247,7 +266,8 @@ const Tag = props => (
                 background: inherit;
                 border-style: solid;
                 border-width: 1px 1px 1px 1px;
-                &:hover {
+                &:hover,
```
Comment (montezume) [inline src/components/tag/tag.js]: 👍

File: src/components/tag/tag.js [hunk 2]
```diff
@@ -283,10 +284,6 @@ const Tag = props => (
               `,
               props.isDisabled &&
                 css`
-                  &:hover {
```
Comment (jonnybel) [inline src/components/tag/tag.js]: This isn't needed because when a button is disabled in the HTML, the `hover` and `focus` states no longer apply.
