### PR TITLE
fix(date-range-input): localize day names

### LINKED ISSUE #917: No keys for MC dashboard Calendar
**No keys for MC dashboard Calendar**

Calendar section of MC Dashboard cannot be translated because we don't have corresponding strings for them in Transifex. 

**I am not sure what the process of adding keys to TX is, so if anyone could help me I'd appreciate that**

**Screenshots**
dashboard dropdown calendar

### PR DESCRIPTION
**Pull request by montezume**
Fixes #917

### CODE REVIEW

File: src/components/inputs/date-range-input/date-range-input.js [hunk 1]
```diff
@@ -325,7 +325,8 @@ class DateRangeCalendar extends React.Component {
             const paddingDayCount = getPaddingDayCount(this.state.calendarDate);
             const paddingDays = Array(paddingDayCount).fill();
 
-            const weekdays = getWeekdayNames('en');
```
Comment (montezume) [inline src/components/inputs/date-range-input/date-range-input.js]: 🤣

Comment (emmenko) [reply src/components/inputs/date-range-input/date-range-input.js]: 🤦‍♂️
