### PR TITLE
fix(time-input): readonly fix

### LINKED ISSUE #723: TimeInput doesn't support `isReadOnly`
Related to #695.

### PR DESCRIPTION
**Pull request by montezume**
This PRd does two things

* Properly support the `isReadOnly` prop for the `TimeInput` component.
* Refactor `TimeInput` component to use design tokens and to be themeable. 

NOTE: Until we merge `10.0.0`, a themed TimeInput looks a bit weird because the icons aren't themable. 

Closes #723

### CODE REVIEW

**Comment by montezume** [comment]
@tdeekens I opened it as a draft so I could see the Percy diff and finish it up. 😢

File: src/components/inputs/time-input/time-input-body.js [hunk 1]
```diff
@@ -78,17 +79,21 @@ export default class TimeInputBody extends React.Component {
...
             disabled={this.props.isDisabled}
+            readOnly={this.props.isReadOnly}
             value={this.props.value}
             onChange={this.props.onChange}
             onFocus={this.props.onFocus}
             onBlur={this.props.onBlur}
             {...filterDataAttributes(this.props)}
             /* ARIA */
             role="textbox"
+            aria-readonly={this.props.isReadOnly}
```
Comment (montezume) [inline src/components/inputs/time-input/time-input-body.js]: same as we do in the TextInput

File: src/components/inputs/time-input/time-input-body.js [hunk 2]
```diff
@@ -20,7 +20,7 @@ const getIconTheme = (isDisabled, isMouseOver) => {
 export const ClearSection = props => (
   <div
     onClick={props.isDisabled || props.isReadOnly ? undefined : props.onClear}
-    css={getClearSectionStyles(props)}
+    css={theme => getClearSectionStyles(props, theme)}
```
Comment (tdeekens) [inline src/components/inputs/time-input/time-input-body.js]: If only if was curried :)

Comment (montezume) [reply src/components/inputs/time-input/time-input-body.js]: at least I have VRT to catch my mistakes 🙈

**Comment by montezume** [comment]
Just need to refactor the icons to use colors from css instead of Icon Themes to make theming work

**Comment by montezume** [comment]
Actually a better way would just be to support Icon Theming.
